In [1]:
import numpy as np
import random
a = np.random.randint(20,size = 10)
print(a)

[17 11 16  2  5  0  3 18  7 16]


In [2]:
a = np.random.randint(1,20,size =(10,10))
a

array([[16,  1,  8,  1,  3, 13, 12, 15, 18, 16],
       [12, 11, 10, 15, 18, 14, 11,  4,  9,  8],
       [15,  8, 18, 12, 10, 12, 11, 10,  8,  5],
       [ 2, 18, 13, 10,  7,  7, 12,  7, 13, 14],
       [ 3, 19, 11, 15, 19,  7, 18, 19, 15,  6],
       [ 6, 16,  1,  9,  4,  3, 16, 17, 12, 15],
       [ 2,  2, 13,  4,  6,  9,  7,  9,  9, 14],
       [ 6,  1, 18, 18, 14,  1, 19, 14,  2,  8],
       [16,  3,  4,  7, 12, 10, 15,  1,  9, 12],
       [ 3,  3,  3,  9,  4,  8, 11, 15,  9, 11]])

In [3]:
a = np.random.randint(1,20,size=(5,10,15))
a

array([[[ 9,  8, 13, 18, 16,  4, 14,  1,  4, 19,  8,  1,  1, 17, 11],
        [19,  7, 11,  6, 19, 10, 16, 11,  8, 12,  4, 14,  3,  9,  8],
        [12,  6,  7,  9,  6,  6, 16, 16, 12, 10, 17,  6, 16, 11, 12],
        [14, 13, 13, 18, 18, 15, 11,  5,  3, 18, 18, 16,  9,  8,  6],
        [ 8,  5,  7, 18, 16, 18, 14, 19,  1,  4, 17, 12, 13, 17, 16],
        [16, 12,  9,  9,  1,  5,  8,  7,  1,  7,  4, 10, 10, 14,  4],
        [ 1, 12, 15,  2,  3,  4,  8, 19,  5, 11, 19, 10, 18, 13,  5],
        [17, 13,  2, 18, 18,  6,  9,  4,  3,  8,  3,  4,  3, 14,  7],
        [ 3, 11,  4, 15, 12, 17, 10, 12, 12,  1,  7, 12,  1, 10, 14],
        [14,  4, 12, 13,  6,  6, 14,  7,  6,  3, 10, 19,  3,  3,  8]],

       [[18, 16, 15, 17,  5,  7,  7, 16, 12,  2, 11, 11, 16, 12,  7],
        [ 5,  8,  7, 14,  1, 18, 10, 12, 18, 13,  5,  3,  2, 14, 18],
        [19,  9,  1, 16, 15,  9, 11, 14,  7, 18,  2,  4,  8, 19,  5],
        [ 9,  4,  4,  4,  9,  7,  6,  4,  5, 18, 16,  9,  5, 16, 12],
        [ 8, 13,  

In [5]:
a[:2,:3]
a

array([[[ 9,  8, 13, 18, 16,  4, 14,  1,  4, 19,  8,  1,  1, 17, 11],
        [19,  7, 11,  6, 19, 10, 16, 11,  8, 12,  4, 14,  3,  9,  8],
        [12,  6,  7,  9,  6,  6, 16, 16, 12, 10, 17,  6, 16, 11, 12],
        [14, 13, 13, 18, 18, 15, 11,  5,  3, 18, 18, 16,  9,  8,  6],
        [ 8,  5,  7, 18, 16, 18, 14, 19,  1,  4, 17, 12, 13, 17, 16],
        [16, 12,  9,  9,  1,  5,  8,  7,  1,  7,  4, 10, 10, 14,  4],
        [ 1, 12, 15,  2,  3,  4,  8, 19,  5, 11, 19, 10, 18, 13,  5],
        [17, 13,  2, 18, 18,  6,  9,  4,  3,  8,  3,  4,  3, 14,  7],
        [ 3, 11,  4, 15, 12, 17, 10, 12, 12,  1,  7, 12,  1, 10, 14],
        [14,  4, 12, 13,  6,  6, 14,  7,  6,  3, 10, 19,  3,  3,  8]],

       [[18, 16, 15, 17,  5,  7,  7, 16, 12,  2, 11, 11, 16, 12,  7],
        [ 5,  8,  7, 14,  1, 18, 10, 12, 18, 13,  5,  3,  2, 14, 18],
        [19,  9,  1, 16, 15,  9, 11, 14,  7, 18,  2,  4,  8, 19,  5],
        [ 9,  4,  4,  4,  9,  7,  6,  4,  5, 18, 16,  9,  5, 16, 12],
        [ 8, 13,  

In [13]:
a = np.array([[2,6],[8,3],[1,9],[6,8]])
a


array([[2, 6],
       [8, 3],
       [1, 9],
       [6, 8]])

In [10]:
a[2,1]

9

In [12]:
a[0:3]

array([[2, 6],
       [8, 3],
       [1, 9]])

In [14]:
#shape
a.shape

(4, 2)

In [15]:
#reshape
a.reshape(2,4)

array([[2, 6, 8, 3],
       [1, 9, 6, 8]])

In [16]:
b =np.array([[9,4],[5,4],[2,9]])
c = np.concatenate([a,b])
c

array([[2, 6],
       [8, 3],
       [1, 9],
       [6, 8],
       [9, 4],
       [5, 4],
       [2, 9]])

In [19]:
#horizantal_shape
a = np.array([[10],[20]])
b = np.array([[1,2,3],[4,5,6]])
np.hstack([b,a])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [20]:
#vertical_shape
a = np.array([[7,8,9],[0,9,8]])
np.vstack([b,a])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 9, 8]])

In [21]:
#reverse
c = np.flip(a)
c

array([[8, 9, 0],
       [9, 8, 7]])

In [55]:
   # 0,1,2,3,4,5,6,7,8,9
a = [1,2,3,4,5,6,7,8,9,10]
m,n,p = np.split(a,[3,4])
print(m,n,p)

[1 2 3] [4] [ 5  6  7  8  9 10]


In [60]:
a=np.array([[1,2],[3,4],[5,6]])
a.sum()

21

In [61]:
a.min()

1

In [62]:
a.max()

6

In [67]:
a.max(axis=0)

array([5, 6])